{% set name = "paseos" %}
{% set org = "aidotse" %}
{% set version = "0.1.3" %}
{% set sha256 = "d90006b72537069aa9c80adde416be04371ff77085af0ffe5ef9300fe8c3d7d2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed --ignore-requires-python .

requirements:
  host:
    - python >=3.8,<4
    - pip
    - setuptools 
  run:
    - python >=3.8,<4
    - dotmap >=1.3.30
    - loguru >=0.6.0
    - matplotlib-base >=3.6.0
    - numpy ==1.23.5
    - pykep >=2.6
    - scikit-spatial >=6.5.0
    - skyfield >=1.45
    - toml >=0.10.2
    - tqdm >=4.64.1

test:
  imports:
    - paseos
  requires:
    - pytest
    - pytest-asyncio
  source_files:
    - paseos/tests
  commands:
    #- pip check # Note this leads to problems with pykep not being found, likely as pykep on pip is discontinued
    - pytest --ignore paseos/tests/visualization_test.py

about:
  home: https://github.com/aidotse/paseos
  summary: A package which simulates the space environment for operating multiple spacecraft.
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE
  doc_url: https://paseos.readthedocs.io/en/latest/
  dev_url: https://github.com/aidotse/paseos/

extra:
  recipe-maintainers:
    - gomezzz
